### PR TITLE
Cosign 3.2.0: apache 2.4 patches from master.

### PR DESCRIPTION
**Pull request by kabalin**
This is just master branch patches applied ontop of 3.2.0 stable branch to make it compile with no errors for Apache 2.4.

### CODE REVIEW

**Comment by AaronMcHale** [comment]
We use Apache 2.4 on Ubuntu, and when trying to build this patch using "make filters" we get the following error:

```
mod_cosign.c: In function 'cosign_handler':
mod_cosign.c:349:16: error: 'conn_rec {aka struct conn_rec}' has no member named 'remote_ip'
   r->connection->COSIGN_CLIENT_IP, r->server );
                ^
mod_cosign.c: In function 'cosign_auth':
mod_cosign.c:537:16: error: 'conn_rec {aka struct conn_rec}' has no member named 'remote_ip'
   r->connection->COSIGN_CLIENT_IP, r->server );
                ^
apxs:Error: Command failed with rc=65536
```

Any advise would be appreciated

Thanks
Aaron

**Comment by kabalin** [comment]
Are you user you are compiling it for 2.4? What is the exact version number?

**Comment by AaronMcHale** [comment]
Version is Apache/2.4.18 (Ubuntu)

Thanks
Aaron

**Comment by kabalin** [comment]
Added fixes for 2.4.18+
This builds fine on Debian Stretch apache-dev 2.4.25-3.

@AaronMcHale try building again on Ubuntu and let me know if there are issues.
